language: java

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2


addons:
  apt_packages:
    - build-essential
    - libboost-all-dev

jdk: openjdk7

script:
  - ./build
  - cd target/cppwrap/build
  - ./showinf test.fake
  - ./minimum_writer test.ome.tiff
